version: "3.1"

services:
  db:
    command:
      [
        "pg_dump",
        "-U",
        $$POSTGRES_USER,
        $$POSTGRES_DB,
        "--no-owner",
        # "||",
        # "gzip",
        # "-9",
        # ">>",
        # "/etc/pg_dumps/db-backup.sql.gz",
      ]
    volumes:
      - /etc/pg_dumps/:/etc/pg_dumps/
